<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>blog</title>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-sm">
            <div>Список сообщений:</div>
        <?php
        /** @var $message Message */
        /** @var $user User */

        use App\Model\Eloquent\Message;
        use App\Model\Eloquent\User;

        $user = $this->user;
        $message = $this->message;


        ?>

        <?php if($messages = $this->messages): ?>
            <?php foreach ($messages as $message): ?>
            <div>
                <?php if($user->isAdmin()): ?>
                <div class="admin">
                    <a href="/adminController/deleteMessage/?id=<?=$message->getId();?>">delete</a>
                </div>
                <?php endif;?>
                <?php if($author=$message->getAuthor()): ?>
                    <div class="author"> <?= $author->getLogin(); ?></div>
                <?php else: ?>
                    <div class="author"> Сообщение от удаленного пользователя</div>
                <?php endif; ?>
                <div class="text">  <?= htmlspecialchars(nl2br($message->getText()));?> </div>
                <?php if($message->getImage()): ?>
                <div><img src="/images/<?=$message->getImage();?>" alt="" style="width: 150px;"></div>
                <?php endif; ?>
            </div>
            <?php endforeach;?>
        <?php else: ?>
            <div>Сообщений пока нет</div>
            <?php endif; ?>
            Добавить сообщение
            <form enctype="multipart/form-data" action="/BlogController/addMessage" method="post">
                <label>
                    <textarea style="width: 250px; height: 150px;" type="text" value="" name="text"></textarea>
                </label><br><br>
                Изображение: <input type="file" name="image"><br>
                <input type="submit" value="Отправить">
                <button name="button" value="">
                    <a href="/BlogController/logout">Выйти</a>
                </button>
            </form>
</body>
</html>