
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Login</title>
</head>
<body>
<?php if(!$this->user): ?>
<div class="container">
    <div class="row">
        <div class="col-sm">
            <!--login -->
            <form method="post" action="/UserController/auth">
                <div>Login</div> </br>
                <label>
                    <div>email</div>
                    <input type="email" name="email" placeholder="email">
                </label>
                <br><br>
                <label>
                    <div>Password</div>
                    <input type="password" name="password" placeholder="password">
                </label>
                <div>
                    <button>Отправить</button>
                </div>
            </form>
<?php else: ?>
             Вы вошли как <?=$this->user->getLogin()?>
            <?php endif ?>

</body>
</html>
