<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <h3><?=$this->title;?></h3>
    <?php
    /** @var \App\Model\User $user */
    $user = $this->user;
    ?>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm">
<!--Registration -->
<form method="post" action="/UserController/register">
    <div>Registration</div> </br>
    <label>
        <div>Email</div>
        <input type="email" name="email" placeholder="email">
    </label>
    <br><br>
    <label>
        <div>Login</div>
        <input type="text" name="login" placeholder="login">
    </label>
    <br><br>
    <label>
        <div>Password</div>
        <input type="password" name="password" placeholder="password">
    </label>

    <div>Введидете пароль второй раз</div>
    <label>
    <input type="password" name="password2" placeholder="password">
    </label>
    <div>
        <button>Отправить</button>
    </div>
</form>
</body>
</html>